jenkins:
  image: jenkins:latest
  ports:
   - "8080:8080"
   - "50000:50000"
  volumes:
   - ${dockerJenkinsHome}:/var/jenkins_home
  links:
   - nexus
   - gerrit
nexus:
  image: sonatype/nexus:oss
  ports:
   - "8081:8081"
  volumes:
   - ${dockerNexusHome}:/sonatype-work
gerrit:
  image: gerritforge/gerrit-ubuntu15.04
  ports:
   - "8082:8080"
   - "29418:29418"
  volumes:
   - ${dockerGerritHome}:/var/gerrit/review_site
