name: Simulated Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Simulate deployment
        run: |
          echo "Starting simulated deployment..."
          echo "Project files:"
          ls -la
          echo "Deploy successful (simulation)."
